"use client"

import { SectionLayout } from "@/components/gallery/SectionLayout"
import type { GalleryItem } from "@/lib/types/gallery"

export default function AIAgentsPage() {
  const aiAgentsContent: GalleryItem[] = [
    {
      id: "customer-service-agent",
      title: "Customer Service AI Agent",
      description: "Intelligent customer support with natural language processing",
      category: "Customer Service",
      version: "v3.2.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Retail", "Financial Services", "Technology"],
      valueChains: ["Customer Service", "Customer Experience"],
      processes: ["Customer Support", "Issue Resolution"],
      capabilities: ["NLP", "Conversational AI", "Sentiment Analysis"],
      fitScore: 94,
      linkedKPIs: ["Customer Satisfaction", "Response Time", "Resolution Rate"],
      linkedPainPoints: ["Long wait times", "Inconsistent service", "High support costs"],
      businessValue: "Reduce response time by 85% and improve customer satisfaction by 45%",
      implementationSteps: [
        "Define conversation flows and intents",
        "Train NLP models with customer data",
        "Integrate with existing support systems",
        "Deploy and monitor performance",
      ],
      requirements: ["Customer support data", "CRM integration", "Chat platform"],
      tags: ["Customer Service", "Conversational AI", "NLP"],
    },
    {
      id: "sales-assistant",
      title: "AI Sales Assistant",
      description: "Automated lead qualification and sales support",
      category: "Sales",
      version: "v2.8.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Manufacturing", "Financial Services"],
      valueChains: ["Sales & Marketing", "Customer Acquisition"],
      processes: ["Lead Qualification", "Sales Support"],
      capabilities: ["Lead Scoring", "Sales Analytics", "CRM Integration"],
      fitScore: 91,
      linkedKPIs: ["Lead Conversion Rate", "Sales Cycle Time", "Revenue Growth"],
      linkedPainPoints: ["Poor lead quality", "Manual qualification", "Missed opportunities"],
      businessValue: "Increase lead conversion by 60% and reduce qualification time by 70%",
      implementationSteps: [
        "Integrate with CRM and marketing systems",
        "Configure lead scoring algorithms",
        "Set up automated workflows",
        "Train sales team on AI insights",
      ],
      requirements: ["CRM system", "Sales data", "Marketing automation platform"],
      tags: ["Sales Automation", "Lead Qualification", "CRM"],
    },
    {
      id: "data-analyst-agent",
      title: "Data Analyst AI Agent",
      description: "Automated data analysis and insight generation",
      category: "Analytics",
      version: "v2.5.3",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Data & Analytics", "Business Intelligence"],
      processes: ["Data Analysis", "Insight Generation"],
      capabilities: ["Statistical Analysis", "Data Visualization", "Predictive Modeling"],
      fitScore: 88,
      linkedKPIs: ["Analysis Speed", "Insight Accuracy", "Decision Quality"],
      linkedPainPoints: ["Manual analysis", "Delayed insights", "Data complexity"],
      businessValue: "Accelerate analysis by 80% and improve insight accuracy by 65%",
      implementationSteps: [
        "Connect to data sources and warehouses",
        "Configure analysis templates",
        "Set up automated reporting",
        "Train users on AI-generated insights",
      ],
      requirements: ["Data warehouse", "Analytics tools", "Business intelligence platform"],
      tags: ["Data Analytics", "Business Intelligence", "Automation"],
    },
    {
      id: "hr-recruiter",
      title: "AI HR Recruiter",
      description: "Intelligent candidate screening and interview scheduling",
      category: "Human Resources",
      version: "v1.9.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Healthcare", "Financial Services"],
      valueChains: ["Human Resources", "Talent Acquisition"],
      processes: ["Candidate Screening", "Interview Management"],
      capabilities: ["Resume Parsing", "Candidate Matching", "Interview Scheduling"],
      fitScore: 86,
      linkedKPIs: ["Time to Hire", "Candidate Quality", "Recruiter Productivity"],
      linkedPainPoints: ["Manual screening", "Scheduling conflicts", "Bias in selection"],
      businessValue: "Reduce time to hire by 50% and improve candidate quality by 40%",
      implementationSteps: [
        "Integrate with ATS and job boards",
        "Configure screening criteria",
        "Set up automated scheduling",
        "Train HR team on AI recommendations",
      ],
      requirements: ["ATS system", "Job posting platforms", "Calendar integration"],
      tags: ["HR Automation", "Talent Acquisition", "Recruitment"],
    },
    {
      id: "financial-advisor",
      title: "AI Financial Advisor",
      description: "Personalized financial planning and investment advice",
      category: "Finance",
      version: "v2.3.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Financial Services", "Insurance", "Wealth Management"],
      valueChains: ["Financial Services", "Wealth Management"],
      processes: ["Financial Planning", "Investment Advisory"],
      capabilities: ["Portfolio Analysis", "Risk Assessment", "Financial Modeling"],
      fitScore: 89,
      linkedKPIs: ["Portfolio Performance", "Client Satisfaction", "AUM Growth"],
      linkedPainPoints: ["Generic advice", "Limited advisor availability", "High advisory costs"],
      businessValue: "Improve portfolio performance by 25% and reduce advisory costs by 60%",
      implementationSteps: [
        "Integrate with financial data providers",
        "Configure risk profiling algorithms",
        "Set up portfolio optimization",
        "Deploy client-facing interface",
      ],
      requirements: ["Financial data feeds", "Portfolio management system", "Compliance framework"],
      tags: ["Financial Planning", "Investment Advisory", "Wealth Management"],
    },
    {
      id: "project-manager",
      title: "AI Project Manager",
      description: "Automated project planning and resource allocation",
      category: "Project Management",
      version: "v1.7.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Construction", "Manufacturing"],
      valueChains: ["Project Management", "Operations"],
      processes: ["Project Planning", "Resource Management"],
      capabilities: ["Project Scheduling", "Resource Optimization", "Risk Management"],
      fitScore: 85,
      linkedKPIs: ["Project Success Rate", "Resource Utilization", "Time to Delivery"],
      linkedPainPoints: ["Poor planning", "Resource conflicts", "Project delays"],
      businessValue: "Improve project success rate by 35% and reduce delivery time by 30%",
      implementationSteps: [
        "Integrate with project management tools",
        "Configure resource allocation algorithms",
        "Set up automated scheduling",
        "Train project teams on AI insights",
      ],
      requirements: ["Project management software", "Resource data", "Team calendars"],
      tags: ["Project Management", "Resource Planning", "Automation"],
    },
    {
      id: "content-moderator",
      title: "AI Content Moderator",
      description: "Automated content review and policy enforcement",
      category: "Content Management",
      version: "v2.1.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Social Media", "Gaming", "E-commerce"],
      valueChains: ["Content Management", "Brand Safety"],
      processes: ["Content Moderation", "Policy Enforcement"],
      capabilities: ["Content Analysis", "Policy Detection", "Automated Actions"],
      fitScore: 92,
      linkedKPIs: ["Moderation Accuracy", "Response Time", "Policy Compliance"],
      linkedPainPoints: ["Manual moderation", "Inconsistent enforcement", "Scalability issues"],
      businessValue: "Improve moderation accuracy by 90% and reduce response time by 95%",
      implementationSteps: [
        "Define content policies and rules",
        "Train AI models on content examples",
        "Set up automated workflows",
        "Monitor and refine performance",
      ],
      requirements: ["Content management system", "Policy guidelines", "Moderation tools"],
      tags: ["Content Moderation", "Policy Enforcement", "Automation"],
    },
    {
      id: "research-assistant",
      title: "AI Research Assistant",
      description: "Intelligent research and information synthesis",
      category: "Research",
      version: "v1.6.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Academia", "Consulting", "Healthcare"],
      valueChains: ["Research & Development", "Knowledge Management"],
      processes: ["Research", "Information Synthesis"],
      capabilities: ["Information Retrieval", "Document Analysis", "Knowledge Synthesis"],
      fitScore: 87,
      linkedKPIs: ["Research Speed", "Information Quality", "Insight Generation"],
      linkedPainPoints: ["Time-consuming research", "Information overload", "Manual synthesis"],
      businessValue: "Accelerate research by 75% and improve information quality by 55%",
      implementationSteps: [
        "Connect to research databases",
        "Configure search and analysis algorithms",
        "Set up synthesis workflows",
        "Train researchers on AI capabilities",
      ],
      requirements: ["Research databases", "Document repositories", "Knowledge management system"],
      tags: ["Research Automation", "Information Synthesis", "Knowledge Management"],
    },
    {
      id: "quality-inspector",
      title: "AI Quality Inspector",
      description: "Automated quality control and defect detection",
      category: "Quality Assurance",
      version: "v2.4.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Manufacturing", "Automotive", "Electronics"],
      valueChains: ["Quality Management", "Manufacturing"],
      processes: ["Quality Control", "Defect Detection"],
      capabilities: ["Computer Vision", "Defect Classification", "Quality Analytics"],
      fitScore: 93,
      linkedKPIs: ["Defect Detection Rate", "Quality Score", "Production Efficiency"],
      linkedPainPoints: ["Manual inspection", "Inconsistent quality", "High defect rates"],
      businessValue: "Improve defect detection by 95% and reduce quality costs by 40%",
      implementationSteps: [
        "Install vision systems and sensors",
        "Train AI models on defect examples",
        "Integrate with production systems",
        "Set up quality dashboards",
      ],
      requirements: ["Vision systems", "Production data", "Quality management system"],
      tags: ["Quality Control", "Computer Vision", "Manufacturing"],
    },
    {
      id: "legal-assistant",
      title: "AI Legal Assistant",
      description: "Contract analysis and legal document review",
      category: "Legal",
      version: "v1.8.3",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Legal Services", "Financial Services", "Real Estate"],
      valueChains: ["Legal Services", "Compliance"],
      processes: ["Document Review", "Contract Analysis"],
      capabilities: ["Document Analysis", "Legal Research", "Contract Intelligence"],
      fitScore: 84,
      linkedKPIs: ["Review Speed", "Accuracy Rate", "Cost Reduction"],
      linkedPainPoints: ["Manual document review", "High legal costs", "Slow turnaround"],
      businessValue: "Reduce document review time by 80% and legal costs by 50%",
      implementationSteps: [
        "Integrate with document management systems",
        "Train AI on legal documents",
        "Configure review workflows",
        "Set up compliance monitoring",
      ],
      requirements: ["Document management system", "Legal databases", "Compliance framework"],
      tags: ["Legal Tech", "Document Analysis", "Contract Intelligence"],
    },
    {
      id: "marketing-agent",
      title: "AI Marketing Agent",
      description: "Automated campaign optimization and audience targeting",
      category: "Marketing",
      version: "v2.6.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Retail", "Technology", "E-commerce"],
      valueChains: ["Marketing & Sales", "Customer Acquisition"],
      processes: ["Campaign Management", "Audience Targeting"],
      capabilities: ["Campaign Optimization", "Audience Segmentation", "Performance Analytics"],
      fitScore: 90,
      linkedKPIs: ["Campaign ROI", "Conversion Rate", "Customer Acquisition Cost"],
      linkedPainPoints: ["Poor targeting", "Low campaign ROI", "Manual optimization"],
      businessValue: "Improve campaign ROI by 65% and reduce acquisition costs by 45%",
      implementationSteps: [
        "Integrate with marketing platforms",
        "Configure audience segmentation",
        "Set up automated optimization",
        "Deploy performance monitoring",
      ],
      requirements: ["Marketing automation platform", "Customer data", "Analytics tools"],
      tags: ["Marketing Automation", "Campaign Optimization", "Audience Targeting"],
    },
    {
      id: "security-monitor",
      title: "AI Security Monitor",
      description: "Intelligent threat detection and incident response",
      category: "Security",
      version: "v3.1.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Financial Services", "Healthcare", "Technology"],
      valueChains: ["Cybersecurity", "Risk Management"],
      processes: ["Threat Detection", "Incident Response"],
      capabilities: ["Anomaly Detection", "Threat Intelligence", "Automated Response"],
      fitScore: 96,
      linkedKPIs: ["Threat Detection Rate", "Response Time", "Security Incidents"],
      linkedPainPoints: ["Undetected threats", "Slow response", "False positives"],
      businessValue: "Improve threat detection by 90% and reduce response time by 85%",
      implementationSteps: [
        "Deploy security monitoring tools",
        "Configure threat detection algorithms",
        "Set up automated response workflows",
        "Train security team on AI insights",
      ],
      requirements: ["SIEM system", "Security tools", "Threat intelligence feeds"],
      tags: ["Cybersecurity", "Threat Detection", "Incident Response"],
    },
  ]

  return (
    <SectionLayout
      title="AI Agents"
      description="Intelligent autonomous agents for business process automation"
      content={aiAgentsContent}
      categoryColor="var(--red-100)"
      searchPlaceholder="Search AI agents..."
      basePath="/gallery/ai-agents"
    />
  )
}
