"use client"
import { SectionLayout } from "@/components/gallery/SectionLayout"
import type { GalleryItem } from "@/lib/types/gallery"

export default function AcceleratorsSectionPage() {
  const acceleratorsContent: GalleryItem[] = [
    {
      id: "sap-btp-starter",
      title: "SAP BTP Starter Kit",
      description: "Complete development environment setup for SAP BTP",
      category: "Template",
      version: "v3.1.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "manufacturing"],
      valueChains: ["I2M", "P2F"],
      processes: ["development", "deployment"],
      capabilities: ["cloud-development", "platform-setup"],
      fitScore: 88,
      linkedKPIs: ["development-speed", "deployment-time"],
      linkedPainPoints: ["complex-setup", "environment-inconsistency"],
      businessValue: "Reduce development setup time by 75% and ensure consistent environments",
      implementationSteps: [
        "Install BTP CLI and dependencies",
        "Configure development environment",
        "Set up CI/CD pipelines",
        "Deploy sample applications",
      ],
      requirements: ["SAP BTP account", "Development tools", "CI/CD platform"],
      tags: ["BTP", "Development", "Template"],
    },
    {
      id: "microservices-template",
      title: "Microservices Architecture Template",
      description: "Production-ready microservices boilerplate",
      category: "Template",
      version: "v2.4.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["architecture-design", "service-development"],
      capabilities: ["microservices", "containerization"],
      fitScore: 92,
      linkedKPIs: ["service-reliability", "deployment-frequency"],
      linkedPainPoints: ["monolithic-architecture", "scaling-challenges"],
      businessValue: "Improve system scalability by 300% and reduce deployment risks by 60%",
      implementationSteps: [
        "Define service boundaries",
        "Set up container orchestration",
        "Implement service mesh",
        "Configure monitoring and logging",
      ],
      requirements: ["Container platform", "Service mesh", "Monitoring tools"],
      tags: ["Microservices", "Architecture", "Scalability"],
    },
    {
      id: "ci-cd-pipeline",
      title: "CI/CD Pipeline Generator",
      description: "Automated deployment pipeline configuration",
      category: "CLI",
      version: "v1.8.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "manufacturing"],
      valueChains: ["I2M", "P2F"],
      processes: ["continuous-integration", "deployment"],
      capabilities: ["automation", "pipeline-management"],
      fitScore: 85,
      linkedKPIs: ["deployment-frequency", "lead-time"],
      linkedPainPoints: ["manual-deployments", "deployment-errors"],
      businessValue: "Increase deployment frequency by 500% and reduce deployment errors by 80%",
      implementationSteps: [
        "Define pipeline stages",
        "Configure automated testing",
        "Set up deployment automation",
        "Implement monitoring and rollback",
      ],
      requirements: ["Version control", "CI/CD platform", "Testing framework"],
      tags: ["CI/CD", "Automation", "DevOps"],
    },
    {
      id: "api-gateway-connector",
      title: "API Gateway Connector",
      description: "Seamless API integration and management",
      category: "Connector",
      version: "v2.6.0",
      license: "Proprietary",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["api-integration", "api-management"],
      capabilities: ["api-gateway", "integration"],
      fitScore: 90,
      linkedKPIs: ["api-latency", "api-reliability"],
      linkedPainPoints: ["api-inconsistency", "api-security"],
      businessValue: "Enhance API reliability by 90% and reduce latency by 50%",
      implementationSteps: [
        "Configure API gateway",
        "Set up API security",
        "Implement rate limiting",
        "Monitor API performance",
      ],
      requirements: ["API gateway platform", "Security tools", "Monitoring tools"],
      tags: ["API Gateway", "Integration", "Security"],
    },
    {
      id: "data-migration-tool",
      title: "Data Migration Accelerator",
      description: "Automated data migration and transformation",
      category: "CLI",
      version: "v1.9.3",
      license: "MIT",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["data-migration", "data-transformation"],
      capabilities: ["data-migration", "data-integration"],
      fitScore: 87,
      linkedKPIs: ["migration-time", "data-integrity"],
      linkedPainPoints: ["manual-migration", "data-loss"],
      businessValue: "Decrease data migration time by 60% and ensure data integrity",
      implementationSteps: [
        "Define data migration strategy",
        "Automate data extraction",
        "Transform data formats",
        "Validate data integrity",
      ],
      requirements: ["Data migration platform", "Transformation tools", "Validation tools"],
      tags: ["Data Migration", "Transformation", "Data Integrity"],
    },
    {
      id: "ml-training-notebook",
      title: "ML Training Notebook Suite",
      description: "Pre-configured machine learning development environment",
      category: "Notebook",
      version: "v2.2.1",
      license: "Apache-2.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["ml-model-training", "ml-model-deployment"],
      capabilities: ["ml-training", "ml-deployment"],
      fitScore: 91,
      linkedKPIs: ["training-time", "deployment-time"],
      linkedPainPoints: ["resource-intensive-training", "deployment-challenges"],
      businessValue: "Accelerate ML model training by 40% and streamline deployment",
      implementationSteps: [
        "Set up ML training environment",
        "Train ML models",
        "Deploy ML models",
        "Monitor model performance",
      ],
      requirements: ["ML training platform", "Deployment tools", "Monitoring tools"],
      tags: ["ML Training", "Deployment", "Machine Learning"],
    },
    {
      id: "security-scanner",
      title: "Security Vulnerability Scanner",
      description: "Automated security assessment and reporting",
      category: "CLI",
      version: "v1.5.0",
      license: "GPL-3.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["security-assessment", "vulnerability-reporting"],
      capabilities: ["security-scanning", "vulnerability-management"],
      fitScore: 89,
      linkedKPIs: ["security-assessment-time", "vulnerability-resolution-time"],
      linkedPainPoints: ["manual-security-assessment", "vulnerability-overlook"],
      businessValue: "Reduce security assessment time by 70% and improve vulnerability resolution",
      implementationSteps: [
        "Configure security scanner",
        "Run security assessments",
        "Generate vulnerability reports",
        "Resolve identified vulnerabilities",
      ],
      requirements: ["Security scanner platform", "Assessment tools", "Reporting tools"],
      tags: ["Security Scanner", "Assessment", "Vulnerability Management"],
    },
    {
      id: "monitoring-dashboard",
      title: "Monitoring Dashboard Template",
      description: "Real-time application monitoring and alerting",
      category: "Template",
      version: "v2.7.2",
      license: "MIT",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["application-monitoring", "alerting"],
      capabilities: ["real-time-monitoring", "alerting"],
      fitScore: 93,
      linkedKPIs: ["response-time", "uptime"],
      linkedPainPoints: ["lack-of-monitoring", "slow-response"],
      businessValue: "Ensure 99.9% uptime and reduce response time by 30%",
      implementationSteps: [
        "Set up monitoring dashboard",
        "Configure monitoring metrics",
        "Set up alerting rules",
        "Analyze monitoring data",
      ],
      requirements: ["Monitoring platform", "Alerting tools", "Analytics tools"],
      tags: ["Monitoring Dashboard", "Alerting", "Uptime"],
    },
    {
      id: "database-connector",
      title: "Multi-Database Connector",
      description: "Universal database connectivity and ORM",
      category: "Connector",
      version: "v3.0.1",
      license: "Apache-2.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["database-connection", "orm-configuration"],
      capabilities: ["multi-database", "orm"],
      fitScore: 94,
      linkedKPIs: ["connection-time", "data-access-speed"],
      linkedPainPoints: ["database-incompatibility", "slow-data-access"],
      businessValue: "Support multiple databases and improve data access speed by 50%",
      implementationSteps: [
        "Install database connector",
        "Configure database connections",
        "Set up ORM",
        "Optimize data access",
      ],
      requirements: ["Database platforms", "ORM tools", "Development tools"],
      tags: ["Database Connector", "ORM", "Multi-Database"],
    },
    {
      id: "testing-framework",
      title: "Automated Testing Framework",
      description: "Comprehensive testing suite and utilities",
      category: "CLI",
      version: "v1.6.4",
      license: "MIT",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["unit-testing", "integration-testing"],
      capabilities: ["automated-testing", "test-coverage"],
      fitScore: 95,
      linkedKPIs: ["test-coverage", "test-execution-time"],
      linkedPainPoints: ["incomplete-test-coverage", "slow-test-execution"],
      businessValue: "Achieve 95% test coverage and reduce test execution time by 40%",
      implementationSteps: [
        "Define test scenarios",
        "Automate test execution",
        "Generate test reports",
        "Analyze test results",
      ],
      requirements: ["Testing platform", "Development tools", "Reporting tools"],
      tags: ["Testing Framework", "Automation", "Test Coverage"],
    },
    {
      id: "deployment-orchestrator",
      title: "Deployment Orchestrator",
      description: "Multi-environment deployment automation",
      category: "CLI",
      version: "v2.3.0",
      license: "Apache-2.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["deployment-automation", "multi-environment-deployment"],
      capabilities: ["deployment-automation", "multi-environment"],
      fitScore: 96,
      linkedKPIs: ["deployment-time", "deployment-failure-rate"],
      linkedPainPoints: ["manual-deployments", "environment-specific-errors"],
      businessValue: "Reduce deployment time by 60% and decrease deployment failure rate by 85%",
      implementationSteps: [
        "Define deployment strategies",
        "Automate deployment processes",
        "Configure environment-specific settings",
        "Monitor deployment outcomes",
      ],
      requirements: ["Deployment platform", "CI/CD tools", "Environment management tools"],
      tags: ["Deployment Orchestrator", "Automation", "Multi-Environment"],
    },
    {
      id: "analytics-notebook",
      title: "Business Analytics Notebook",
      description: "Interactive data analysis and visualization",
      category: "Notebook",
      version: "v1.4.2",
      license: "MIT",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["technology", "financial-services"],
      valueChains: ["I2M", "L2C"],
      processes: ["data-analysis", "data-visualization"],
      capabilities: ["interactive-analysis", "data-visualization"],
      fitScore: 97,
      linkedKPIs: ["analysis-time", "insight-generation"],
      linkedPainPoints: ["static-analysis", "slow-insight-generation"],
      businessValue: "Accelerate analysis time by 50% and generate insights 2x faster",
      implementationSteps: [
        "Set up analytics notebook",
        "Import data sources",
        "Perform data analysis",
        "Visualize data insights",
      ],
      requirements: ["Analytics platform", "Data visualization tools", "Data sources"],
      tags: ["Analytics Notebook", "Analysis", "Visualization"],
    },
  ]

  return (
    <SectionLayout
      title="Development Accelerators"
      description="Templates, tools, and connectors to accelerate development workflows"
      content={acceleratorsContent}
      categoryColor="var(--yellow-100)"
      searchPlaceholder="Search accelerators..."
      basePath="/gallery/accelerators-section"
    />
  )
}
