"use client"

import { SectionLayout } from "@/components/gallery/SectionLayout"
import type { GalleryItem } from "@/lib/types/gallery"

export default function SignavioPage() {
  const signavioContent: GalleryItem[] = [
    {
      id: "process-mining-starter",
      title: "Process Mining Starter",
      description: "Quick setup for process discovery and analysis",
      category: "Template",
      version: "v2.1.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["manufacturing", "financial-services"],
      valueChains: ["S2P", "R2R"],
      processes: ["procurement", "accounts-payable"],
      capabilities: ["process-discovery", "compliance-monitoring"],
      fitScore: 85,
      linkedKPIs: ["cycle-time", "cost-per-transaction"],
      linkedPainPoints: ["manual-processes", "compliance-gaps"],
      businessValue: "Reduce process discovery time by 60% and improve compliance visibility",
      implementationSteps: [
        "Connect to source systems",
        "Configure process mining algorithms",
        "Set up dashboards and alerts",
        "Train users on insights interpretation",
      ],
    },
    {
      id: "bpmn-workflow-designer",
      title: "BPMN Workflow Designer",
      description: "Visual workflow modeling and automation",
      category: "Tool",
      version: "v3.0.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["healthcare", "retail"],
      valueChains: ["L2C", "P2F"],
      processes: ["order-fulfillment", "customer-onboarding"],
      capabilities: ["workflow-automation", "process-modeling"],
      fitScore: 92,
      linkedKPIs: ["automation-rate", "process-efficiency"],
      linkedPainPoints: ["manual-handoffs", "process-inconsistency"],
      businessValue: "Automate 70% of routine workflows and standardize process execution",
      implementationSteps: [
        "Map current state processes",
        "Design future state workflows",
        "Configure automation rules",
        "Deploy and monitor workflows",
      ],
    },
    {
      id: "compliance-dashboard",
      title: "Compliance Dashboard",
      description: "Real-time compliance monitoring and reporting",
      category: "Dashboard",
      version: "v1.5.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["financial-services", "pharmaceuticals"],
      valueChains: ["R2R", "GOV"],
      processes: ["regulatory-reporting", "audit-management"],
      capabilities: ["compliance-monitoring", "risk-assessment"],
      fitScore: 78,
      linkedKPIs: ["compliance-score", "audit-findings"],
      linkedPainPoints: ["regulatory-complexity", "audit-preparation"],
      businessValue: "Achieve 95% compliance score and reduce audit preparation time by 50%",
      implementationSteps: [
        "Define compliance requirements",
        "Set up monitoring rules",
        "Configure alerts and reports",
        "Establish governance workflows",
      ],
    },
    {
      id: "process-optimization",
      title: "Process Optimization Kit",
      description: "AI-powered process improvement recommendations",
      category: "AI Tool",
      version: "v2.3.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["manufacturing", "financial-services"],
      valueChains: ["S2P", "R2R"],
      processes: ["procurement", "accounts-payable"],
      capabilities: ["process-discovery", "compliance-monitoring"],
      fitScore: 85,
      linkedKPIs: ["cycle-time", "cost-per-transaction"],
      linkedPainPoints: ["manual-processes", "compliance-gaps"],
      businessValue: "Reduce process discovery time by 60% and improve compliance visibility",
      implementationSteps: [
        "Connect to source systems",
        "Configure process mining algorithms",
        "Set up dashboards and alerts",
        "Train users on insights interpretation",
      ],
    },
    {
      id: "task-automation",
      title: "Task Automation Engine",
      description: "Automated task execution and monitoring",
      category: "Engine",
      version: "v1.8.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["healthcare", "retail"],
      valueChains: ["L2C", "P2F"],
      processes: ["order-fulfillment", "customer-onboarding"],
      capabilities: ["workflow-automation", "process-modeling"],
      fitScore: 92,
      linkedKPIs: ["automation-rate", "process-efficiency"],
      linkedPainPoints: ["manual-handoffs", "process-inconsistency"],
      businessValue: "Automate 70% of routine workflows and standardize process execution",
      implementationSteps: [
        "Map current state processes",
        "Design future state workflows",
        "Configure automation rules",
        "Deploy and monitor workflows",
      ],
    },
    {
      id: "analytics-suite",
      title: "Process Analytics Suite",
      description: "Advanced analytics for process performance",
      category: "Analytics",
      version: "v2.0.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["financial-services", "pharmaceuticals"],
      valueChains: ["R2R", "GOV"],
      processes: ["regulatory-reporting", "audit-management"],
      capabilities: ["compliance-monitoring", "risk-assessment"],
      fitScore: 78,
      linkedKPIs: ["compliance-score", "audit-findings"],
      linkedPainPoints: ["regulatory-complexity", "audit-preparation"],
      businessValue: "Achieve 95% compliance score and reduce audit preparation time by 50%",
      implementationSteps: [
        "Define compliance requirements",
        "Set up monitoring rules",
        "Configure alerts and reports",
        "Establish governance workflows",
      ],
    },
    {
      id: "integration-hub",
      title: "SAP Integration Hub",
      description: "Seamless SAP system integration",
      category: "Integration",
      version: "v1.9.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["manufacturing", "financial-services"],
      valueChains: ["S2P", "R2R"],
      processes: ["procurement", "accounts-payable"],
      capabilities: ["process-discovery", "compliance-monitoring"],
      fitScore: 85,
      linkedKPIs: ["cycle-time", "cost-per-transaction"],
      linkedPainPoints: ["manual-processes", "compliance-gaps"],
      businessValue: "Reduce process discovery time by 60% and improve compliance visibility",
      implementationSteps: [
        "Connect to source systems",
        "Configure process mining algorithms",
        "Set up dashboards and alerts",
        "Train users on insights interpretation",
      ],
    },
    {
      id: "mobile-app",
      title: "Mobile Process App",
      description: "Mobile interface for process management",
      category: "Mobile",
      version: "v1.4.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["healthcare", "retail"],
      valueChains: ["L2C", "P2F"],
      processes: ["order-fulfillment", "customer-onboarding"],
      capabilities: ["workflow-automation", "process-modeling"],
      fitScore: 92,
      linkedKPIs: ["automation-rate", "process-efficiency"],
      linkedPainPoints: ["manual-handoffs", "process-inconsistency"],
      businessValue: "Automate 70% of routine workflows and standardize process execution",
      implementationSteps: [
        "Map current state processes",
        "Design future state workflows",
        "Configure automation rules",
        "Deploy and monitor workflows",
      ],
    },
    {
      id: "reporting-engine",
      title: "Advanced Reporting Engine",
      description: "Customizable reports and visualizations",
      category: "Reporting",
      version: "v2.2.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["financial-services", "pharmaceuticals"],
      valueChains: ["R2R", "GOV"],
      processes: ["regulatory-reporting", "audit-management"],
      capabilities: ["compliance-monitoring", "risk-assessment"],
      fitScore: 78,
      linkedKPIs: ["compliance-score", "audit-findings"],
      linkedPainPoints: ["regulatory-complexity", "audit-preparation"],
      businessValue: "Achieve 95% compliance score and reduce audit preparation time by 50%",
      implementationSteps: [
        "Define compliance requirements",
        "Set up monitoring rules",
        "Configure alerts and reports",
        "Establish governance workflows",
      ],
    },
    {
      id: "workflow-templates",
      title: "Workflow Templates Library",
      description: "Pre-built templates for common processes",
      category: "Templates",
      version: "v1.6.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["manufacturing", "financial-services"],
      valueChains: ["S2P", "R2R"],
      processes: ["procurement", "accounts-payable"],
      capabilities: ["process-discovery", "compliance-monitoring"],
      fitScore: 85,
      linkedKPIs: ["cycle-time", "cost-per-transaction"],
      linkedPainPoints: ["manual-processes", "compliance-gaps"],
      businessValue: "Reduce process discovery time by 60% and improve compliance visibility",
      implementationSteps: [
        "Connect to source systems",
        "Configure process mining algorithms",
        "Set up dashboards and alerts",
        "Train users on insights interpretation",
      ],
    },
    {
      id: "api-connector",
      title: "API Connector Suite",
      description: "Connect external systems via APIs",
      category: "Connector",
      version: "v2.1.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["healthcare", "retail"],
      valueChains: ["L2C", "P2F"],
      processes: ["order-fulfillment", "customer-onboarding"],
      capabilities: ["workflow-automation", "process-modeling"],
      fitScore: 92,
      linkedKPIs: ["automation-rate", "process-efficiency"],
      linkedPainPoints: ["manual-handoffs", "process-inconsistency"],
      businessValue: "Automate 70% of routine workflows and standardize process execution",
      implementationSteps: [
        "Map current state processes",
        "Design future state workflows",
        "Configure automation rules",
        "Deploy and monitor workflows",
      ],
    },
    {
      id: "security-module",
      title: "Security & Governance Module",
      description: "Enhanced security and governance controls",
      category: "Security",
      version: "v1.7.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["financial-services", "pharmaceuticals"],
      valueChains: ["R2R", "GOV"],
      processes: ["regulatory-reporting", "audit-management"],
      capabilities: ["compliance-monitoring", "risk-assessment"],
      fitScore: 78,
      linkedKPIs: ["compliance-score", "audit-findings"],
      linkedPainPoints: ["regulatory-complexity", "audit-preparation"],
      businessValue: "Achieve 95% compliance score and reduce audit preparation time by 50%",
      implementationSteps: [
        "Define compliance requirements",
        "Set up monitoring rules",
        "Configure alerts and reports",
        "Establish governance workflows",
      ],
    },
  ]

  return (
    <SectionLayout
      title="Signavio Solutions"
      description="Process mining, workflow automation, and business process management tools"
      content={signavioContent}
      categoryColor="var(--blue-100)"
      searchPlaceholder="Search Signavio solutions..."
      basePath="/gallery/signavio"
    />
  )
}
