"use client"
import { SectionLayout } from "@/components/gallery/SectionLayout"
import type { GalleryItem } from "@/lib/types/gallery"

export default function WalkMePage() {
  const walkmeContent: GalleryItem[] = [
    {
      id: "onboarding-flows",
      title: "User Onboarding Flows",
      description: "Interactive guided tours for new users",
      category: "Onboarding",
      version: "v3.2.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Experience", "Digital Transformation"],
      processes: ["User Adoption", "Training & Development"],
      capabilities: ["Digital Guidance", "User Experience"],
      fitScore: 85,
      linkedKPIs: ["User Adoption Rate", "Time to Value", "Support Ticket Reduction"],
      linkedPainPoints: ["Poor user adoption", "High support costs", "Complex interfaces"],
      businessValue: "Reduce onboarding time by 60% and increase feature adoption by 40%",
      implementationSteps: [
        "Install WalkMe browser extension",
        "Create guided tour flows",
        "Configure user segmentation",
        "Deploy and monitor adoption",
      ],
      requirements: ["WalkMe platform license", "Admin access to target application"],
      tags: ["Onboarding", "User Experience", "Digital Adoption"],
    },
    {
      id: "feature-adoption",
      title: "Feature Adoption Toolkit",
      description: "Drive adoption of new features and capabilities",
      category: "Adoption",
      version: "v2.8.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Manufacturing", "Retail"],
      valueChains: ["Product Development", "Customer Experience"],
      processes: ["Change Management", "User Training"],
      capabilities: ["Feature Rollout", "User Engagement"],
      fitScore: 78,
      linkedKPIs: ["Feature Adoption Rate", "User Engagement Score", "Training Completion Rate"],
      linkedPainPoints: ["Low feature utilization", "Resistance to change", "Training inefficiency"],
      businessValue: "Increase new feature adoption by 50% within first month of release",
      implementationSteps: [
        "Identify target features for promotion",
        "Create contextual guidance flows",
        "Set up analytics tracking",
        "Launch adoption campaigns",
      ],
      requirements: ["WalkMe Digital Adoption Platform", "Feature usage analytics"],
      tags: ["Feature Adoption", "Change Management", "User Engagement"],
    },
    {
      id: "help-center",
      title: "Interactive Help Center",
      description: "Self-service support with guided assistance",
      category: "Support",
      version: "v1.9.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Service", "Support Operations"],
      processes: ["Self-Service Support", "Knowledge Management"],
      capabilities: ["Help Documentation", "Interactive Guidance"],
      fitScore: 72,
      linkedKPIs: ["Self-Service Resolution Rate", "Support Ticket Deflection", "User Satisfaction"],
      linkedPainPoints: ["High support volume", "Repetitive support requests", "Poor self-service adoption"],
      businessValue: "Reduce support tickets by 35% through improved self-service capabilities",
      implementationSteps: [
        "Audit existing help content",
        "Create interactive help flows",
        "Integrate with support systems",
        "Monitor usage and optimize",
      ],
      requirements: ["WalkMe platform", "Existing help documentation", "Support system integration"],
      tags: ["Self-Service", "Support", "Knowledge Management"],
    },
    {
      id: "workflow-guidance",
      title: "Workflow Guidance System",
      description: "Step-by-step process guidance",
      category: "Guidance",
      version: "v2.5.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Manufacturing", "Healthcare", "Financial Services"],
      valueChains: ["Operations", "Quality Management"],
      processes: ["Process Standardization", "Quality Assurance"],
      capabilities: ["Process Guidance", "Workflow Automation"],
      fitScore: 88,
      linkedKPIs: ["Process Compliance Rate", "Error Reduction", "Task Completion Time"],
      linkedPainPoints: ["Process inconsistency", "High error rates", "Complex workflows"],
      businessValue: "Improve process compliance by 45% and reduce errors by 30%",
      implementationSteps: [
        "Map critical business processes",
        "Create step-by-step guidance",
        "Implement validation checkpoints",
        "Deploy and monitor compliance",
      ],
      requirements: ["WalkMe platform", "Process documentation", "System integrations"],
      tags: ["Process Guidance", "Compliance", "Workflow"],
    },
    {
      id: "analytics-dashboard",
      title: "User Analytics Dashboard",
      description: "Track user engagement and completion rates",
      category: "Analytics",
      version: "v1.7.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Retail"],
      valueChains: ["Data & Analytics", "Customer Experience"],
      processes: ["Performance Monitoring", "User Behavior Analysis"],
      capabilities: ["Analytics", "Reporting"],
      fitScore: 75,
      linkedKPIs: ["User Engagement Score", "Completion Rates", "Usage Analytics"],
      linkedPainPoints: ["Lack of user insights", "Poor engagement tracking", "Limited analytics"],
      businessValue: "Gain 360° visibility into user behavior and optimize experiences",
      implementationSteps: [
        "Configure analytics tracking",
        "Set up custom dashboards",
        "Define key metrics",
        "Create automated reports",
      ],
      requirements: ["WalkMe Analytics module", "Data visualization tools"],
      tags: ["Analytics", "User Insights", "Performance Tracking"],
    },
    {
      id: "mobile-guidance",
      title: "Mobile App Guidance",
      description: "Native mobile app user guidance",
      category: "Mobile",
      version: "v2.1.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Retail", "Financial Services", "Healthcare"],
      valueChains: ["Mobile Experience", "Customer Engagement"],
      processes: ["Mobile Onboarding", "App Adoption"],
      capabilities: ["Mobile Guidance", "Cross-Platform Support"],
      fitScore: 82,
      linkedKPIs: ["Mobile App Adoption", "Mobile User Engagement", "App Store Ratings"],
      linkedPainPoints: ["Poor mobile adoption", "Complex mobile interfaces", "High app abandonment"],
      businessValue: "Increase mobile app engagement by 55% and reduce abandonment by 40%",
      implementationSteps: [
        "Integrate WalkMe Mobile SDK",
        "Design mobile-optimized flows",
        "Test across devices",
        "Deploy and monitor performance",
      ],
      requirements: ["WalkMe Mobile SDK", "Mobile app development access"],
      tags: ["Mobile", "App Guidance", "User Experience"],
    },
    {
      id: "smart-tips",
      title: "Smart Tips Engine",
      description: "Contextual tips and recommendations",
      category: "AI",
      version: "v1.4.3",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Experience", "Digital Transformation"],
      processes: ["User Adoption", "Training & Development"],
      capabilities: ["Digital Guidance", "User Experience"],
      fitScore: 85,
      linkedKPIs: ["User Adoption Rate", "Time to Value", "Support Ticket Reduction"],
      linkedPainPoints: ["Poor user adoption", "High support costs", "Complex interfaces"],
      businessValue: "Reduce onboarding time by 60% and increase feature adoption by 40%",
      implementationSteps: [
        "Install WalkMe browser extension",
        "Create guided tour flows",
        "Configure user segmentation",
        "Deploy and monitor adoption",
      ],
      requirements: ["WalkMe platform license", "Admin access to target application"],
      tags: ["Onboarding", "User Experience", "Digital Adoption"],
    },
    {
      id: "survey-builder",
      title: "In-App Survey Builder",
      description: "Collect user feedback within applications",
      category: "Feedback",
      version: "v2.0.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Experience", "Digital Transformation"],
      processes: ["User Adoption", "Training & Development"],
      capabilities: ["Digital Guidance", "User Experience"],
      fitScore: 85,
      linkedKPIs: ["User Adoption Rate", "Time to Value", "Support Ticket Reduction"],
      linkedPainPoints: ["Poor user adoption", "High support costs", "Complex interfaces"],
      businessValue: "Reduce onboarding time by 60% and increase feature adoption by 40%",
      implementationSteps: [
        "Install WalkMe browser extension",
        "Create guided tour flows",
        "Configure user segmentation",
        "Deploy and monitor adoption",
      ],
      requirements: ["WalkMe platform license", "Admin access to target application"],
      tags: ["Onboarding", "User Experience", "Digital Adoption"],
    },
    {
      id: "automation-rules",
      title: "Automation Rules Engine",
      description: "Automated user guidance based on behavior",
      category: "Automation",
      version: "v1.6.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Experience", "Digital Transformation"],
      processes: ["User Adoption", "Training & Development"],
      capabilities: ["Digital Guidance", "User Experience"],
      fitScore: 85,
      linkedKPIs: ["User Adoption Rate", "Time to Value", "Support Ticket Reduction"],
      linkedPainPoints: ["Poor user adoption", "High support costs", "Complex interfaces"],
      businessValue: "Reduce onboarding time by 60% and increase feature adoption by 40%",
      implementationSteps: [
        "Install WalkMe browser extension",
        "Create guided tour flows",
        "Configure user segmentation",
        "Deploy and monitor adoption",
      ],
      requirements: ["WalkMe platform license", "Admin access to target application"],
      tags: ["Onboarding", "User Experience", "Digital Adoption"],
    },
    {
      id: "integration-kit",
      title: "Enterprise Integration Kit",
      description: "Connect with enterprise systems and workflows",
      category: "Integration",
      version: "v2.3.1",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Experience", "Digital Transformation"],
      processes: ["User Adoption", "Training & Development"],
      capabilities: ["Digital Guidance", "User Experience"],
      fitScore: 85,
      linkedKPIs: ["User Adoption Rate", "Time to Value", "Support Ticket Reduction"],
      linkedPainPoints: ["Poor user adoption", "High support costs", "Complex interfaces"],
      businessValue: "Reduce onboarding time by 60% and increase feature adoption by 40%",
      implementationSteps: [
        "Install WalkMe browser extension",
        "Create guided tour flows",
        "Configure user segmentation",
        "Deploy and monitor adoption",
      ],
      requirements: ["WalkMe platform license", "Admin access to target application"],
      tags: ["Onboarding", "User Experience", "Digital Adoption"],
    },
    {
      id: "content-manager",
      title: "Content Management System",
      description: "Manage and organize guidance content",
      category: "Content",
      version: "v1.8.2",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Experience", "Digital Transformation"],
      processes: ["User Adoption", "Training & Development"],
      capabilities: ["Digital Guidance", "User Experience"],
      fitScore: 85,
      linkedKPIs: ["User Adoption Rate", "Time to Value", "Support Ticket Reduction"],
      linkedPainPoints: ["Poor user adoption", "High support costs", "Complex interfaces"],
      businessValue: "Reduce onboarding time by 60% and increase feature adoption by 40%",
      implementationSteps: [
        "Install WalkMe browser extension",
        "Create guided tour flows",
        "Configure user segmentation",
        "Deploy and monitor adoption",
      ],
      requirements: ["WalkMe platform license", "Admin access to target application"],
      tags: ["Onboarding", "User Experience", "Digital Adoption"],
    },
    {
      id: "performance-insights",
      title: "Performance Insights",
      description: "Advanced analytics and performance metrics",
      category: "Insights",
      version: "v2.2.0",
      demoVideo: "/placeholder.svg?height=200&width=300",
      industries: ["Technology", "Financial Services", "Healthcare"],
      valueChains: ["Customer Experience", "Digital Transformation"],
      processes: ["User Adoption", "Training & Development"],
      capabilities: ["Digital Guidance", "User Experience"],
      fitScore: 85,
      linkedKPIs: ["User Adoption Rate", "Time to Value", "Support Ticket Reduction"],
      linkedPainPoints: ["Poor user adoption", "High support costs", "Complex interfaces"],
      businessValue: "Reduce onboarding time by 60% and increase feature adoption by 40%",
      implementationSteps: [
        "Install WalkMe browser extension",
        "Create guided tour flows",
        "Configure user segmentation",
        "Deploy and monitor adoption",
      ],
      requirements: ["WalkMe platform license", "Admin access to target application"],
      tags: ["Onboarding", "User Experience", "Digital Adoption"],
    },
  ]

  return (
    <SectionLayout
      title="WalkMe Solutions"
      description="Digital adoption platform for user onboarding and guidance"
      content={walkmeContent}
      categoryColor="var(--green-100)"
      searchPlaceholder="Search WalkMe solutions..."
      basePath="/gallery/walkme"
    />
  )
}
